---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/batikbuy/public_html/
      - /bin/cp/ index.php $DEPLOYPATH
      - /bin/cp/ .editorconfig $DEPLOYPATH
      - /bin/cp/ .htaccess $DEPLOYPATH
      - /bin/cp/ license.php $DEPLOYPATH
      - /bin/cp/ readme.txt $DEPLOYPATH
      - /bin/cp/ composser.jason $DEPLOYPAT
      - /bin/cp/ .gitignore $DEPLOYPATH
      - /bin/cp -R application DEPLOYPATH
      - /bin/cp/ -R assets $DEPLOYPATH
      - /bin/cp/ -R system $DEPLOYPATH